modulo1/aula-git/sobre-mim/minha-bio.txt
=> Minha Biografia

modulo1/aula-git/sobre-mim/musicas.txt
=> Minhas musicas

modulo1/aula-git/sobre-mim/filmes.txt
=> Meus filmes

modulo1/aula-git/sobre-mim/redes-sociais.txt
=> Minhas redes sociais

modulo1/projeto-readme/aprendizados.md
=> aprendizado.md

modulo1/strings-arrays/template_javascript/index.html, modulo1/strings-arrays/template_javascript/index.js
=> Exercicios arrays

modulo1/objetos/index.html, modulo1/objetos/index.js, modulo1/operadores/template_javascript/index.js
=> Exercícios objetos

modulo1/funcoes-de-array/index.html, modulo1/funcoes-de-array/index.js
=> Funções de Array

modulo1/resolvendo-problemas/resolvendo-problema.txt
=> Resolvendo problemas

modulo5/revisao-javascript-backend/backend/exercicio1/index.js, modulo5/revisao-javascript-backend/backend/exercicio2/index.js, modulo5/revisao-javascript-backend/backend/exercicio3/index.js, modulo5/revisao-javascript-backend/backend/exercicio4/exercicio.js
Revisão JavaScript para Back-end
=> Revisão JS

modulo5/aprofundamento-typescript/.gitignore, modulo5/aprofundamento-typescript/package-lock.json, modulo5/aprofundamento-typescript/package.json, modulo5/aprofundamento-typescript/src/exercicio1.ts, modulo5/aprofundamento-typescript/src/exercicio2.ts, modulo5/aprofundamento-typescript/src/exercicio3.ts, modulo5/aprofundamento-typescript/src/exercicio4.ts, modulo5/aprofundamento-typescript/src/exercicio5.ts, modulo5/aprofundamento-typescript/src/exercicio6.ts, modulo5/aprofundamento-typescript/tsconfig.json
Exercícios de Aprofundamento TypeScript
=> Aprofundamento typescript

modulo5/intro-express/.gitignore, modulo5/intro-express/package-lock.json, modulo5/intro-express/package.json, modulo5/intro-express/src/data.ts, modulo5/intro-express/src/index.ts, modulo5/intro-express/tsconfig.json
=> Intro express

modulo5/aprofundamento-express/src/index.ts
=> não funcional

modulo5/aprofundamento-expressDois/package-lock.json, modulo5/aprofundamento-expressDois/package.json, modulo5/aprofundamento-expressDois/src/data.ts, modulo5/aprofundamento-expressDois/src/index.ts, modulo5/aprofundamento-expressDois/tsconfig.json
=> Aprofundamento express2

modulo5/fluxo-de-dados-backend/.gitignore, modulo5/fluxo-de-dados-backend/package-lock.json, modulo5/fluxo-de-dados-backend/package.json, modulo5/fluxo-de-dados-backend/src/data.ts, modulo5/fluxo-de-dados-backend/src/index.ts, modulo5/fluxo-de-dados-backend/tsconfig.json
=> Fluxo de dados backend

modulo5/aprofundamento-sql/MySQL
=> Aprofundamento SQL

modulo6/classes-encapsulamento/template-classes-encapsulamento/.gitignore, modulo6/classes-encapsulamento/template-classes-encapsulamento/package-lock.json, modulo6/classes-encapsulamento/template-classes-encapsulamento/package.json, modulo6/classes-encapsulamento/template-classes-encapsulamento/requests.rest, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/class/Product.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/class/ProductDataBase.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/class/Purchase.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/class/PurchaseDataBase.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/class/User.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/class/UserDataBase.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/database/connection.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/database/data.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/database/migrations.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/database/tableNames.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/endpoints/createProduct.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/endpoints/createPurchase.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/endpoints/createUser.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/endpoints/getProducts.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/endpoints/getUserPurchases.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/endpoints/getUsers.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/endpoints/ping.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/index.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/models/Product.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/models/Purchase.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/src/models/User.ts, modulo6/classes-encapsulamento/template-classes-encapsulamento/tsconfig.json
exercícios entregue atrasado por conta do trabalho na vida pessoal, já foi comentado com algumas pessoas da Labenu.
=> Classes encapsulamento

modulo6/heranca-encapsulamento/.gitignore, modulo6/heranca-encapsulamento/package-lock.json, modulo6/heranca-encapsulamento/package.json, modulo6/heranca-encapsulamento/requests.rest, modulo6/heranca-encapsulamento/src/database/BaseDatabase.ts, modulo6/heranca-encapsulamento/src/database/ProductDataBase.ts, modulo6/heranca-encapsulamento/src/database/PurchaseDateBase.ts, modulo6/heranca-encapsulamento/src/database/UserDatabase.ts, modulo6/heranca-encapsulamento/src/database/connection.ts, modulo6/heranca-encapsulamento/src/database/data.ts, modulo6/heranca-encapsulamento/src/database/migrations.ts, modulo6/heranca-encapsulamento/src/database/tableNames.ts, modulo6/heranca-encapsulamento/src/endpoints/createProduct.ts, modulo6/heranca-encapsulamento/src/endpoints/createPurchase.ts, modulo6/heranca-encapsulamento/src/endpoints/createUser.ts, modulo6/heranca-encapsulamento/src/endpoints/getProducts.ts, modulo6/heranca-encapsulamento/src/endpoints/getUserPurchases.ts, modulo6/heranca-encapsulamento/src/endpoints/getUsers.ts, modulo6/heranca-encapsulamento/src/endpoints/ping.ts, modulo6/heranca-encapsulamento/src/index.ts, modulo6/heranca-encapsulamento/src/models/Product.ts, modulo6/heranca-encapsulamento/src/models/Purchase.ts, modulo6/heranca-encapsulamento/src/models/User.ts, modulo6/heranca-encapsulamento/tsconfig.json
Não deletei a pasta Connection por conta das Migrations, iria levar um tempo, e como estou atrasado na matéria preferir deixar por assim.. Porém não tem connection em nenhum dos endpoints..
=> Herancao encapsulamento

modulo6/arquitetura-de-software-1/.gitignore, modulo6/arquitetura-de-software-1/README.md, modulo6/arquitetura-de-software-1/package-lock.json, modulo6/arquitetura-de-software-1/package.json, modulo6/arquitetura-de-software-1/request.rest, modulo6/arquitetura-de-software-1/src/app.ts, modulo6/arquitetura-de-software-1/src/business/DeleteBusiness.ts, modulo6/arquitetura-de-software-1/src/business/UserBusiness.ts, modulo6/arquitetura-de-software-1/src/business/findUserBusiness.ts, modulo6/arquitetura-de-software-1/src/controller/DeleteController.ts, modulo6/arquitetura-de-software-1/src/controller/FindUserController.ts, modulo6/arquitetura-de-software-1/src/controller/findUserControlle.ts, modulo6/arquitetura-de-software-1/src/controller/userController.ts, modulo6/arquitetura-de-software-1/src/data/BaseDatabase.ts, modulo6/arquitetura-de-software-1/src/data/userDataBase.ts, modulo6/arquitetura-de-software-1/src/index.ts, modulo6/arquitetura-de-software-1/tsconfig.json
=> Exercicio faltando apenas o delete que irei fazer amanhã

modulo6/arquitetura-software-2/.gitignore, modulo6/arquitetura-software-2/package-lock.json, modulo6/arquitetura-software-2/package.json, modulo6/arquitetura-software-2/queries.sql, modulo6/arquitetura-software-2/request.rest, modulo6/arquitetura-software-2/src/app.ts, modulo6/arquitetura-software-2/src/business/MovieBusiness.ts, modulo6/arquitetura-software-2/src/business/UserBusiness.ts, modulo6/arquitetura-software-2/src/controller/MovieController.ts, modulo6/arquitetura-software-2/src/controller/UserController.ts, modulo6/arquitetura-software-2/src/data/BaseDatabase.ts, modulo6/arquitetura-software-2/src/data/MovieDatabase.ts, modulo6/arquitetura-software-2/src/data/UserDatabase.ts, modulo6/arquitetura-software-2/src/index.ts, modulo6/arquitetura-software-2/src/routes/movieRouter.ts, modulo6/arquitetura-software-2/src/routes/userRouter.ts, modulo6/arquitetura-software-2/src/types/User.ts, modulo6/arquitetura-software-2/tsconfig.json
Exercício completo, apenas com uma duvida que depois irei perguntar!
=> Exercício completo

modulo6/arquitetura-software-3/.gitignore, modulo6/arquitetura-software-3/package-lock.json, modulo6/arquitetura-software-3/package.json, modulo6/arquitetura-software-3/queries.sql, modulo6/arquitetura-software-3/request.rest, modulo6/arquitetura-software-3/src/app.ts, modulo6/arquitetura-software-3/src/business/MovieBusiness.ts, modulo6/arquitetura-software-3/src/business/UserBusiness.ts, modulo6/arquitetura-software-3/src/controller/MovieController.ts, modulo6/arquitetura-software-3/src/controller/UserController.ts, modulo6/arquitetura-software-3/src/data/BaseDatabase.ts, modulo6/arquitetura-software-3/src/data/MovieDatabase.ts, modulo6/arquitetura-software-3/src/data/UserDatabase.ts, modulo6/arquitetura-software-3/src/error/CustomError.ts, modulo6/arquitetura-software-3/src/error/MovieErrors.ts, modulo6/arquitetura-software-3/src/error/UserErrors.ts, modulo6/arquitetura-software-3/src/index.ts, modulo6/arquitetura-software-3/src/model/User.ts, modulo6/arquitetura-software-3/src/model/creatMovieDTO.ts, modulo6/arquitetura-software-3/src/model/createUserDTO.ts, modulo6/arquitetura-software-3/src/routes/movieRouter.ts, modulo6/arquitetura-software-3/src/routes/userRouter.ts, modulo6/arquitetura-software-3/src/services/idGenerate.ts, modulo6/arquitetura-software-3/tsconfig.json
Exercícios de Sercices, DTO e Custom Errors completo!
=> Exercícios completos
